linters:
    PropertySortOrder:
        enabled: false
    IdSelector:
        enabled: false
    Indentation:
        width: 4
    NestingDepth:
        max_depth: 4
    SelectorDepth:
        max_depth: 4
