linters:
  Indentation:
    enabled: false
  SpaceBeforeBrace:
    enabled: false
  PropertySortOrder:
    enabled: false
  IdSelector:
      enabled: false
  # StringQuotes:
  #   enabled: false
  # UrlQuotes:
  #   enabled: false
