###########################################################################################
#
#  STAGING ENVIRONMENT VARIABLES
#
###########################################################################################

# Just an example use case
# enable_analytics: no

disable_robots: true
enable_analytics: false